using Content.Client.Decals.UI;
using Content.Client.Stylesheets;
using Content.Shared.Decals;
using Content.Shared.SprayPainter.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Numerics;

namespace Content.Client.SprayPainter.UI;

[GenerateTypedNameReferences]
public sealed partial class SprayPainterDecals : Control
{
    public Action<ProtoId<DecalPrototype>>? OnDecalSelected;
    public Action<Color?>? OnColorChanged;
    public Action<int>? OnAngleChanged;
    public Action<bool>? OnSnapChanged;
    public Action<bool>? OnColorPickerToggled;
    public Action<DecalPaintMode>? OnModeChanged;

    private PaletteColorPicker? _palette;
    private SpriteSystem? _sprite;
    private string _selectedDecal = string.Empty;
    private List<SprayPainterDecalEntry> _decals = [];

    public SprayPainterDecals()
    {
        RobustXamlLoader.Load(this);

        AddAngleButton.OnButtonUp += _ => AngleSpinBox.Value = (AngleSpinBox.Value + 90) % 360;
        SubAngleButton.OnButtonUp += _ => AngleSpinBox.Value = (AngleSpinBox.Value - 90) % 360;
        SetZeroAngleButton.OnButtonUp += _ => AngleSpinBox.Value = 0;
        AngleSpinBox.ValueChanged += args => OnAngleChanged?.Invoke(args.Value);

        UseCustomColorCheckBox.OnPressed += _ =>
        {
            OnColorChanged?.Invoke(UseCustomColorCheckBox.Pressed ? ColorSelector.Color : null);
            UpdateColorButtons(UseCustomColorCheckBox.Pressed);
        };
        SnapToTileCheckBox.OnPressed += _ => OnSnapChanged?.Invoke(SnapToTileCheckBox.Pressed);
        ColorSelector.OnColorChanged += OnColorSelected;
        ColorPalette.OnPressed += OnColorPalettePressed;
        ColorPicker.OnPressed += args => OnColorPickerToggled?.Invoke(args.Button.Pressed);

        foreach (var mode in Enum.GetValues<DecalPaintMode>())
            ModeSelector.AddItem(Loc.GetString($"spray-painter-mode-{mode.ToString().ToLowerInvariant()}"), (int) mode);

        ModeSelector.OnItemSelected += args =>
        {
            ModeSelector.SelectId(args.Id);
            OnModeChanged?.Invoke((DecalPaintMode) args.Id);
        };
    }

    public void PopulateDecals(List<SprayPainterDecalEntry> decals, SpriteSystem sprite)
    {
        _sprite ??= sprite;
        _decals = decals;
        DecalsGrid.Children.Clear();

        foreach (var decal in decals)
        {
            var button = new TextureButton
            {
                TextureNormal = sprite.Frame0(decal.Sprite),
                Name = decal.Name,
                ToolTip = decal.Name,
                Scale = new Vector2(2, 2),
                Modulate = UseCustomColorCheckBox.Pressed ? ColorSelector.Color : Color.White,
            };
            button.OnPressed += OnDecalPressed;

            if (_selectedDecal != decal.Name)
            {
                DecalsGrid.AddChild(button);
                continue;
            }

            DecalsGrid.AddChild(new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = StyleNano.ButtonColorDefault },
                Children = { button },
            });
        }
    }

    private void OnColorSelected(Color color)
    {
        if (!UseCustomColorCheckBox.Pressed)
            return;

        OnColorChanged?.Invoke(color);
        UpdateColorButtons(true);
    }

    private void UpdateColorButtons(bool apply)
    {
        var color = apply ? ColorSelector.Color : Color.White;
        foreach (var child in DecalsGrid.Children)
        {
            if (child is TextureButton button)
                button.Modulate = color;
            else if (child is PanelContainer panel)
            {
                foreach (TextureButton selected in panel.Children)
                    selected.Modulate = color;
            }
        }
    }

    private void OnDecalPressed(BaseButton.ButtonEventArgs args)
    {
        if (args.Button.Name is not { } name)
            return;

        _selectedDecal = name;
        SelectedDecalName.Text = name;
        OnDecalSelected?.Invoke(name);

        if (_sprite != null)
            PopulateDecals(_decals, _sprite);
    }

    private void OnColorPalettePressed(BaseButton.ButtonEventArgs _)
    {
        if (_palette == null)
        {
            _palette = new PaletteColorPicker();
            _palette.OpenCenteredLeft();
            _palette.PaletteList.OnItemSelected += args =>
            {
                var color = (args.ItemList.GetSelected().First().Metadata as Color?)!.Value;
                ColorSelector.Color = color;
                OnColorSelected(color);
            };
            return;
        }

        if (_palette.IsOpen)
            _palette.Close();
        else
            _palette.Open();
    }

    public void SetSelectedDecal(string name)
    {
        if (_selectedDecal == name)
            return;

        _selectedDecal = name;
        SelectedDecalName.Text = name;
        if (_sprite != null)
            PopulateDecals(_decals, _sprite);
    }

    public void SetAngle(int degrees) => AngleSpinBox.OverrideValue(degrees);

    public void SetColor(Color? color)
    {
        UseCustomColorCheckBox.Pressed = color != null;
        if (color != null)
            ColorSelector.Color = color.Value;
        UpdateColorButtons(UseCustomColorCheckBox.Pressed);
    }

    public void SetSnap(bool snap) => SnapToTileCheckBox.Pressed = snap;
    public void SetColorPicker(bool enabled) => ColorPicker.Pressed = enabled;
    public void SetMode(DecalPaintMode mode) => ModeSelector.SelectId((int) mode);
}
