using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Shared.Decals;
using Content.Shared.SprayPainter.Components;
using Robust.Shared.Prototypes;

namespace Content.Client.SprayPainter.UI;

[GenerateTypedNameReferences]
public sealed partial class SprayPainterWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    private readonly SpriteSystem _spriteSystem;

    public Action<ItemList.ItemListSelectedEventArgs>? OnSpritePicked;
    public Action<ItemList.ItemListSelectedEventArgs>? OnColorPicked;
    public Action<ProtoId<DecalPrototype>>? OnDecalPicked;
    public Action<Color?>? OnDecalColorChanged;
    public Action<int>? OnDecalAngleChanged;
    public Action<bool>? OnDecalSnapChanged;
    public Action<bool>? OnDecalColorPickerToggled;
    public Action<DecalPaintMode>? OnDecalModeChanged;
    public Dictionary<string, int> ItemColorIndex = new();

    private Dictionary<string, Color> currentPalette = new();
    private const string colorLocKeyPrefix = "pipe-painter-color-";
    private List<SprayPainterEntry> CurrentEntries = new List<SprayPainterEntry>();

    private readonly SpriteSpecifier _colorEntryIconTexture = new SpriteSpecifier.Rsi(
        new ResPath("Structures/Piping/Atmospherics/pipe.rsi"),
        "pipeStraight");

    public SprayPainterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _sysMan.GetEntitySystem<SpriteSystem>();

        DecalControls.OnDecalSelected += decal => OnDecalPicked?.Invoke(decal);
        DecalControls.OnColorChanged += color => OnDecalColorChanged?.Invoke(color);
        DecalControls.OnAngleChanged += angle => OnDecalAngleChanged?.Invoke(angle);
        DecalControls.OnSnapChanged += snap => OnDecalSnapChanged?.Invoke(snap);
        DecalControls.OnColorPickerToggled += toggle => OnDecalColorPickerToggled?.Invoke(toggle);
        DecalControls.OnModeChanged += mode => OnDecalModeChanged?.Invoke(mode);
    }

    private static string GetColorLocString(string? colorKey)
    {
        if (string.IsNullOrEmpty(colorKey))
            return Loc.GetString("pipe-painter-no-color-selected");
        var locKey = colorLocKeyPrefix + colorKey;

        if (!Loc.TryGetString(locKey, out var locString))
            locString = colorKey;

        return locString;
        }

    public string? IndexToColorKey(int index)
    {
        return (string?) ColorList[index].Metadata;
    }

    public void Populate(List<SprayPainterEntry> entries, int selectedStyle, string? selectedColorKey, Dictionary<string, Color> palette)
    {
        // Only clear if the entries change. Otherwise the list would "jump" after selecting an item
        if (!CurrentEntries.Equals(entries))
        {
            CurrentEntries = entries;
            SpriteList.Clear();
            foreach (var entry in entries)
            {
                SpriteList.AddItem(entry.Name, entry.Icon);
            }
        }

        if (!currentPalette.Equals(palette))
        {
            currentPalette = palette;
            ItemColorIndex.Clear();
            ColorList.Clear();

            foreach (var color in palette)
            {
                var locString = GetColorLocString(color.Key);
                var item = ColorList.AddItem(locString, _spriteSystem.Frame0(_colorEntryIconTexture));
                item.IconModulate = color.Value;
                item.Metadata = color.Key;

                ItemColorIndex.Add(color.Key, ColorList.IndexOf(item));
            }
        }

        // Disable event so we don't send a new event for pre-selectedStyle entry and end up in a loop

        if (selectedColorKey != null)
        {
            var index = ItemColorIndex[selectedColorKey];
            ColorList.OnItemSelected -= OnColorPicked;
            ColorList[index].Selected = true;
            ColorList.OnItemSelected += OnColorPicked;
        }

        SpriteList.OnItemSelected -= OnSpritePicked;
        SpriteList[selectedStyle].Selected = true;
        SpriteList.OnItemSelected += OnSpritePicked;
    }

    public void PopulateDecals(List<SprayPainterDecalEntry> decals) =>
        DecalControls.PopulateDecals(decals, _spriteSystem);

    public void SetSelectedDecal(string decal) => DecalControls.SetSelectedDecal(decal);
    public void SetDecalColor(Color? color) => DecalControls.SetColor(color);
    public void SetDecalAngle(int angle) => DecalControls.SetAngle(angle);
    public void SetDecalSnap(bool snap) => DecalControls.SetSnap(snap);
    public void SetDecalColorPicker(bool enabled) => DecalControls.SetColorPicker(enabled);
    public void SetDecalMode(DecalPaintMode mode) => DecalControls.SetMode(mode);
}
