using System.Linq;
using System.Text;
using Content.Shared._Misfits.VaultDoorConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.VaultDoorConsole;

[GenerateTypedNameReferences]
public sealed partial class VaultDoorConsoleWindow : DefaultWindow
{
    private static readonly Color BackgroundColor = Color.FromHex("#080c08");
    private static readonly Color NoiseColor = Color.FromHex("#1f6b2c");
    private static readonly Color WordColor = Color.FromHex("#39ff5c");
    private static readonly Color UsedColor = Color.FromHex("#2a3a2a");
    private static readonly Color DeniedColor = Color.FromHex("#ff4136");
    private static readonly Color GrantedColor = Color.FromHex("#39ff5c");

    private readonly VaultDoorConsoleBoundUserInterface _owner;

    public VaultDoorConsoleWindow(VaultDoorConsoleBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);

        _owner = owner;

        ScreenPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = BackgroundColor };
        FlavorLabel.SetMessage("ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL\nENTER PASSWORD NOW", WordColor);
    }

    public void UpdateState(VaultDoorConsoleBoundUserInterfaceState state)
    {
        var interactable = !state.Solved && !state.LockedOut;

        if (state.Solved)
        {
            var minutes = state.SolvedRemaining is { } solvedRemaining
                ? System.Math.Ceiling(solvedRemaining.TotalMinutes)
                : 0;
            StatusLabel.Text = $"ACCESS GRANTED - DOOR BOLTED OPEN ({minutes} MINUTE(S) REMAINING)";
            StatusLabel.FontColorOverride = GrantedColor;
        }
        else if (state.LockedOut)
        {
            var minutes = state.LockedOutRemaining is { } remaining
                ? System.Math.Ceiling(remaining.TotalMinutes)
                : 0;
            StatusLabel.Text = $"TERMINAL LOCKED - {minutes} MINUTE(S) REMAINING";
            StatusLabel.FontColorOverride = DeniedColor;
        }
        else
        {
            StatusLabel.Text = $"{state.AttemptsRemaining} ATTEMPT(S) LEFT";
            StatusLabel.FontColorOverride = state.AttemptsRemaining <= 1 ? DeniedColor : WordColor;
        }

        BuildColumn(ColumnAContainer, state.ColumnA, interactable);
        BuildColumn(ColumnBContainer, state.ColumnB, interactable);

        var history = new StringBuilder();
        foreach (var line in state.Log)
            history.AppendLine(line);

        HistoryLabel.SetMessage(FormattedMessage.FromMarkupPermissive(history.ToString()), WordColor);
    }

    private void BuildColumn(BoxContainer container, List<List<VaultDoorConsoleSegment>> rows, bool interactable)
    {
        container.RemoveAllChildren();

        foreach (var row in rows)
        {
            var rowBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            foreach (var segment in row)
            {
                if (segment.Kind == VaultDoorConsoleTokenKind.None)
                {
                    var label = new Label
                    {
                        Text = segment.Text,
                        FontColorOverride = NoiseColor,
                    };
                    rowBox.AddChild(label);
                    continue;
                }

                var button = new Button
                {
                    Text = segment.Text,
                    StyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Transparent },
                    Disabled = !interactable || segment.Used,
                };
                button.Label.FontColorOverride = segment.Used ? UsedColor : WordColor;

                var token = segment.Token;
                button.OnPressed += _ => _owner.SendToken(token);

                rowBox.AddChild(button);
            }

            container.AddChild(rowBox);
        }
    }
}
