using Content.Client.UserInterface.Controls;
using Content.Shared.Popups;
using Content.Shared.RCD;
using Content.Shared.RCD.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client.RCD;

[GenerateTypedNameReferences]
public sealed partial class RCDMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly ITileDefinitionManager _tileDefManager = default!;

    private SharedPopupSystem _popup;
    private SpriteSystem _sprites;

    public event Action<ProtoId<RCDPrototype>>? SendRCDSystemMessageAction;

    private EntityUid _owner;

    public RCDMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _popup = _entManager.System<SharedPopupSystem>();
        _sprites = _entManager.System<SpriteSystem>();

        OnChildAdded += AddRCDMenuButtonOnClickActions;
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
        Refresh();
    }

    public void Refresh()
    {
        // Find the main radial container
        var main = FindControl<RadialContainer>("Main");

        // Populate secondary radial containers
        if (!_entManager.TryGetComponent<RCDComponent>(_owner, out var rcd))
            return;

        foreach (var protoId in rcd.AvailablePrototypes)
        {
            if (!_protoManager.TryIndex(protoId, out var proto))
                continue;

            if (proto.Mode == RcdMode.Invalid)
                continue;

            var parent = FindControl<RadialContainer>(proto.Category);
            var tooltip = GetBuildDisplayName(proto);

            tooltip = OopsConcat(char.ToUpper(tooltip[0]).ToString(), tooltip.Remove(0, 1));

            var button = new RCDMenuButton()
            {
                StyleClasses = { "RadialMenuButton" },
                SetSize = new Vector2(64f, 64f),
                ToolTip = tooltip,
                ProtoId = protoId,
            };

            var sprite = GetBuildDisplaySprite(proto);
            if (sprite != null)
            {
                var tex = new TextureRect()
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = _sprites.Frame0(sprite),
                    SetSize = new Vector2(48f, 48f),
                    Stretch = TextureRect.StretchMode.KeepAspectCovered,
                };

                button.AddChild(tex);
            }

            parent.AddChild(button);

            // Ensure that the button that transitions the menu to the associated category layer
            // is visible in the main radial container (as these all start with Visible = false)
            foreach (var child in main.Children)
            {
                var castChild = child as RadialMenuTextureButton;

                if (castChild is not RadialMenuTextureButton)
                    continue;

                if (castChild.TargetLayer == proto.Category)
                {
                    castChild.Visible = true;
                    break;
                }
            }
        }

        // Set up menu actions
        foreach (var child in Children)
        {
            AddRCDMenuButtonOnClickActions(child);
        }
    }

    private static string OopsConcat(string a, string b)
    {
        // This exists to prevent Roslyn being clever and compiling something that fails sandbox checks.
        return a + b;
    }

    private void AddRCDMenuButtonOnClickActions(Control control)
    {
        var radialContainer = control as RadialContainer;

        if (radialContainer == null)
            return;

        foreach (var child in radialContainer.Children)
        {
            var castChild = child as RCDMenuButton;

            if (castChild == null)
                continue;

            castChild.OnButtonUp += _ =>
            {
                SendRCDSystemMessageAction?.Invoke(castChild.ProtoId);

                if (_playerManager.LocalSession?.AttachedEntity != null &&
                    _protoManager.TryIndex(castChild.ProtoId, out var proto))
                {
                    var msg = Loc.GetString("rcd-component-change-mode", ("mode", Loc.GetString(proto.SetName)));

                    if (proto.Mode == RcdMode.ConstructTile || proto.Mode == RcdMode.ConstructObject)
                    {
                        var name = GetBuildDisplayName(proto);
                        msg = Loc.GetString("rcd-component-change-build-mode", ("name", name));
                    }

                    // Popup message
                    _popup.PopupClient(msg, _owner, _playerManager.LocalSession.AttachedEntity);
                }

                Close();
            };
        }
    }

    private string GetBuildDisplayName(RCDPrototype proto)
    {
        if (proto.Prototype != null)
        {
            if (proto.Mode == RcdMode.ConstructObject &&
                _protoManager.TryIndex<EntityPrototype>(proto.Prototype, out var entProto))
                return Loc.GetString(entProto.Name);

            if (proto.Mode == RcdMode.ConstructTile &&
                _tileDefManager.TryGetDefinition(proto.Prototype, out var tileDef))
                return Loc.GetString(tileDef.Name);
        }

        return Loc.GetString(proto.SetName);
    }

    private SpriteSpecifier? GetBuildDisplaySprite(RCDPrototype proto)
    {
        if (proto.Prototype != null)
        {
            if (proto.Mode == RcdMode.ConstructTile &&
                _tileDefManager.TryGetDefinition(proto.Prototype, out var tileDef) &&
                tileDef.Sprite != null)
                return new SpriteSpecifier.Texture(tileDef.Sprite.Value);

            if (proto.Mode == RcdMode.ConstructObject &&
                IsWastelandCategory(proto.Category) &&
                _protoManager.HasIndex<EntityPrototype>(proto.Prototype))
                return new SpriteSpecifier.EntityPrototype(proto.Prototype);
        }

        return proto.Sprite;
    }

    private static bool IsWastelandCategory(string category)
    {
        return category == "WastelandDoors" || category == "WastelandWallsAndFlooring";
    }
}

public sealed class RCDMenuButton : RadialMenuTextureButton
{
    public ProtoId<RCDPrototype> ProtoId { get; set; }

    public RCDMenuButton()
    {

    }
}
