- type: job
  id: NCRMPinvestigator
  setPreference: true
  hideWithoutJobWhitelist: true   # #Misfits Add - admin-only; hidden from job picker without whitelist
  hideIfPlaytimeRequirementsNotMet: false
  jobWhitelistBypassesRoleTimers: true # #Misfits Add - admin bypass, no timer gate
  canBeAntag: false
  name: job-name-ncr-mp-investigator #Misfits Change
  overwatchCategory: OverwatchNcrMp
  description: job-description-ncr-mp-investegator
  playTimeTracker: NCRMPinvestigator
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 216000 # 60 hours
    - !type:CharacterPlaytimeRequirement
      tracker: NCRExecutiveOfficer
      min: 216000 # 60 hours
  startingGear: NCRMPinvestigatorGear
  alwaysUseSpawner: true
  icon: "JobIconNCRMPInvestegator"
  supervisors: job-supervisors-ncr-mp
  access:
  - NCR
  - NCRSGT
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR
      - type: GrantRangerCombat

- type: startingGear
  id: NCRMPinvestigatorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitNCRMP
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head:  N14ClothingHeadHatNCRMPCap
    outerClothing: MisfitsNCRMPCombatArmor
    hands: N14ClothingHandsGlovesCombat
    id: N14IDNCRDogtagMPInvestigator
    ears: N14ClothingHeadsetNCR
    eyes: ClothingEyesGlassesSunglasses

- type: playTimeTracker
  id: NCRMPinvestigator
