using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.Enclave;

[GenerateTypedNameReferences]
public sealed partial class EnclaveRecruitWindow : DefaultWindow
{
    private static readonly Color BackgroundColor = Color.FromHex("#080b06");
    private static readonly Color DocumentColor = Color.FromHex("#11180c");
    private static readonly Color TerminalGreen = Color.FromHex("#9dbf71");
    private static readonly Color HeaderAmber = Color.FromHex("#d6b85a");
    private static readonly Color WarningRed = Color.FromHex("#d65a4a");

    public event Action? OnAccepted;
    public event Action? OnDeclined;

    private string _characterName = string.Empty;

    public EnclaveRecruitWindow()
    {
        RobustXamlLoader.Load(this);

        ScreenPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BackgroundColor,
            BorderColor = HeaderAmber,
            BorderThickness = new Thickness(2),
        };
        DocumentPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = DocumentColor,
            BorderColor = Color.FromHex("#4f5f35"),
            BorderThickness = new Thickness(1),
        };

        TerminalHeader.SetMessage(
            "ROBCO INDUSTRIES UNIFIED OPERATING SYSTEM\n" +
            "EXECUTIVE CONTINUITY AUTHORITY // SECURE ENLISTMENT TERMINAL\n" +
            "CLEARANCE: RESTRICTED     RECORD: 104-E/2296",
            HeaderAmber);

        PageTitle.FontColorOverride = HeaderAmber;
        StatusLabel.FontColorOverride = WarningRed;

        ContinueButton.OnPressed += _ => ShowOath();
        BackButton.OnPressed += _ => ShowContract();
        AcceptButton.OnPressed += _ => OnAccepted?.Invoke();
        DeclineButton.OnPressed += _ => OnDeclined?.Invoke();

        ShowContract();
    }

    public void SetCharacterName(string characterName)
    {
        _characterName = characterName;
        if (BackButton.Visible)
            ShowOath();
    }

    private void ShowContract()
    {
        PageTitle.Text = "DEPARTMENT OF DEFENSE // UNIFORM ENLISTMENT CONTRACT";
        DocumentText.SetMessage(Loc.GetString("enclave-recruit-contract-text"), TerminalGreen);
        StatusLabel.Text = "READ THE COMPLETE CONTRACT BEFORE PROCEEDING.";

        BackButton.Visible = false;
        ContinueButton.Visible = true;
        AcceptButton.Visible = false;
    }

    private void ShowOath()
    {
        PageTitle.Text = "OATH OF IDEOLOGICAL PURITY";
        DocumentText.SetMessage(
            Loc.GetString("enclave-recruit-oath-text", ("name", _characterName)),
            TerminalGreen);
        StatusLabel.Text = "SIGNING CONSTITUTES PERPETUAL AND IRREVOCABLE CONSENT.";

        BackButton.Visible = true;
        ContinueButton.Visible = false;
        AcceptButton.Visible = true;
    }
}
