using Content.Shared._Misfits.Enclave;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._Misfits.Enclave;

[GenerateTypedNameReferences]
public sealed partial class EnclaveDetonatorWindow : DefaultWindow
{
    public event Action? OnRefresh;
    public event Action<NetEntity>? OnActivate;

    public EnclaveDetonatorWindow()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
    }

    public void SetPersonnel(EnclaveMicroBombEntry[] personnel)
    {
        PersonnelList.RemoveAllChildren();
        EmptyLabel.Visible = personnel.Length == 0;
        PersonnelList.Visible = personnel.Length > 0;

        foreach (var person in personnel)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
            };

            row.AddChild(new Label
            {
                Text = $"{person.Name} — {person.Role}",
                HorizontalExpand = true,
                VerticalAlignment = Control.VAlignment.Center,
            });

            var detonate = new Button
            {
                Text = "DETONATE",
                MinWidth = 110,
            };
            detonate.OnPressed += _ => OnActivate?.Invoke(person.Entity);
            row.AddChild(detonate);

            PersonnelList.AddChild(row);
        }
    }
}
