// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Misfits.Genetics.Abilities;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Misfits.Genetics.Abilities;

[GenerateTypedNameReferences]
public sealed partial class TelepathyFarWindow : DefaultWindow
{
    public Action<NetEntity, string>? OnSend;

    private List<TelepathyFarEntry> _players = new();

    public TelepathyFarWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("MutationTelepathy-far-title");
        TargetLabel.Text = Loc.GetString("MutationTelepathy-far-target");
        MessageLabel.Text = Loc.GetString("MutationTelepathy-window-message");
        MessageInput.PlaceHolder = Loc.GetString("MutationTelepathy-window-placeholder");
        SendButton.Text = Loc.GetString("MutationTelepathy-far-send");

        PlayerSelect.OnItemSelected += args => PlayerSelect.SelectId(args.Id);
        SendButton.OnPressed += _ => Send();
        MessageInput.OnTextEntered += _ => Send();
    }

    public void SetPlayers(List<TelepathyFarEntry> players)
    {
        _players = players;
        PlayerSelect.Clear();
        if (players.Count == 0)
        {
            PlayerSelect.AddItem(Loc.GetString("MutationTelepathy-far-nobody"), 0);
            PlayerSelect.Disabled = true;
            SendButton.Disabled = true;
            return;
        }

        PlayerSelect.Disabled = false;
        SendButton.Disabled = false;
        for (var i = 0; i < players.Count; i++)
        {
            PlayerSelect.AddItem(players[i].Name, i);
        }
    }

    private void Send()
    {
        var msg = MessageInput.Text.Trim();
        var id = PlayerSelect.SelectedId;
        if (msg.Length == 0 || id < 0 || id >= _players.Count)
            return;

        OnSend?.Invoke(_players[id].Target, msg);
    }
}
