using Content.Shared._Misfits.FactionWar;
using Content.Client.UserInterface.Controls;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

[GenerateTypedNameReferences]
public sealed partial class WarInviteWindow : FancyWindow
{
    public event Action<string, bool>? OnRespond;

    private string _warKey = string.Empty;

    public WarInviteWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(_warKey))
                return;
            OnRespond?.Invoke(_warKey, true);
        };

        DeclineButton.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(_warKey))
                return;
            OnRespond?.Invoke(_warKey, false);
        };
    }

    public void UpdatePrompt(WarInvitePromptEvent prompt)
    {
        _warKey = prompt.WarKey;
        InviteLabel.SetMarkup(
            $"[bold]{FormattedMessage.EscapeText(prompt.InviterCharacterName)}[/bold] invited you to join [bold]{FormattedMessage.EscapeText(prompt.SideName)}[/bold].\n" +
            "Press Accept to join this war side.");
        ShowResult(true, string.Empty);
    }

    public void ShowResult(bool success, string message)
    {
        if (string.IsNullOrWhiteSpace(message))
        {
            ResultLabel.SetMarkup(string.Empty);
            return;
        }

        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }
}
