using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

[GenerateTypedNameReferences]
public sealed partial class WarSideReviewWindow : FancyWindow
{
    public event Action<string, IReadOnlyList<NetEntity>>? OnSubmit;

    private string _warKey = string.Empty;
    private readonly Dictionary<NetEntity, bool> _removeSelections = new();

    public WarSideReviewWindow()
    {
        RobustXamlLoader.Load(this);

        SubmitButton.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(_warKey))
                return;

            var removed = _removeSelections
                .Where(kvp => kvp.Value)
                .Select(kvp => kvp.Key)
                .ToList();

            OnSubmit?.Invoke(_warKey, removed);
        };
    }

    public void UpdatePrompt(WarSideReviewPromptEvent prompt)
    {
        _warKey = prompt.WarKey;
        _removeSelections.Clear();
        ParticipantsContainer.RemoveAllChildren();

        HeaderLabel.SetMarkup(
            $"[bold]Review side:[/bold] {FormattedMessage.EscapeText(prompt.SideName)}\n" +
            "Default is [bold]Keep[/bold]. Click to mark a participant as [bold]Remove[/bold].");

        if (prompt.Participants.Count == 0)
        {
            ParticipantsContainer.AddChild(new Label
            {
                Text = "No joined participants to review on your side.",
                Margin = new Thickness(4, 2),
                FontColorOverride = Color.Gray,
            });
        }
        else
        {
            foreach (var participant in prompt.Participants)
            {
                _removeSelections[participant.Entity] = false;

                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 8,
                    Margin = new Thickness(2, 2),
                };

                var nameLabel = new Label
                {
                    Text = string.IsNullOrWhiteSpace(participant.JobName)
                        ? participant.CharacterName
                        : $"{participant.CharacterName} ({participant.JobName})",
                    HorizontalExpand = true,
                    ClipText = true,
                };

                var toggleButton = new Button
                {
                    Text = "Keep",
                    Modulate = Color.ForestGreen,
                    MinWidth = 90,
                };

                var entity = participant.Entity;
                toggleButton.OnPressed += _ =>
                {
                    var nowRemove = !_removeSelections[entity];
                    _removeSelections[entity] = nowRemove;
                    toggleButton.Text = nowRemove ? "Remove" : "Keep";
                    toggleButton.Modulate = nowRemove ? Color.IndianRed : Color.ForestGreen;
                };

                row.AddChild(nameLabel);
                row.AddChild(toggleButton);
                ParticipantsContainer.AddChild(row);
            }
        }

        ShowResult(true, string.Empty);
    }

    public void ShowResult(bool success, string message)
    {
        if (string.IsNullOrWhiteSpace(message))
        {
            ResultLabel.SetMarkup(string.Empty);
            return;
        }

        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }
}
