using Content.Shared._Misfits.Silicon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._Misfits.Silicon;

[GenerateTypedNameReferences]
public sealed partial class ZaxLinkedUnitsWindow : DefaultWindow
{
    public event Action? OnRefresh;
    public event Action<NetEntity>? OnWarp;

    public ZaxLinkedUnitsWindow()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
    }

    public void SetUnits(ZaxLinkedUnitEntry[] units)
    {
        UnitList.RemoveAllChildren();
        EmptyLabel.Visible = units.Length == 0;
        UnitList.Visible = units.Length > 0;

        foreach (var unit in units)
        {
            var button = new Button
            {
                Text = $"{unit.Name} [{GetKindName(unit.Kind)}] - {unit.Location}",
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
            };

            button.OnPressed += _ => OnWarp?.Invoke(unit.Entity);
            UnitList.AddChild(button);
        }
    }

    private static string GetKindName(ZaxLinkedUnitKind kind)
    {
        return kind switch
        {
            ZaxLinkedUnitKind.Player => "Player",
            ZaxLinkedUnitKind.GhostRole => "Ghost Role",
            _ => "NPC",
        };
    }
}
