using Content.Shared._Nuclear14.AutodocSirius;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client._Nuclear14.AutodocSirius;

[GenerateTypedNameReferences]
public sealed partial class SiriusAutodocWindow : DefaultWindow
{
    private static readonly Color ColorMinor = Color.FromHex("#33FF33");
    private static readonly Color ColorModerate = Color.FromHex("#FFAA33");
    private static readonly Color ColorSevere = Color.FromHex("#FF5533");
    private static readonly Color ColorCritical = Color.FromHex("#FF3333");
    private static readonly Color ColorDim = Color.FromHex("#1a5c1a");
    private static readonly Color ColorActive = Color.FromHex("#33FF33");
    private static readonly Color ColorInactive = Color.FromHex("#3a5c3a");
    private static readonly Color ColorDisabled = Color.FromHex("#444444");
    private static readonly Color ColorSevered = Color.FromHex("#666666");
    private static readonly Color ColorHealthy = Color.FromHex("#33FF33");
    private readonly Dictionary<string, string> _damageDisplayNames = new()
    {
        { "Blunt", Loc.GetString("autodoc-damage-blunt") },
        { "Slash", Loc.GetString("autodoc-damage-slash") },
        { "Piercing", Loc.GetString("autodoc-damage-piercing") },
        { "Heat", Loc.GetString("autodoc-damage-heat") },
        { "Cold", Loc.GetString("autodoc-damage-cold") },
        { "Shock", Loc.GetString("autodoc-damage-shock") },
        { "Caustic", Loc.GetString("autodoc-damage-caustic") },
        { "Radiation", Loc.GetString("autodoc-damage-radiation") },
        { "Bloodloss", Loc.GetString("autodoc-damage-bloodloss") },
        { "Asphyxiation", Loc.GetString("autodoc-damage-asphyxiation") },
        { "Poison", Loc.GetString("autodoc-damage-poison") },
        { "Toxins", Loc.GetString("autodoc-damage-toxins") },
        { "Genetic", Loc.GetString("autodoc-damage-genetic") },
        { "Cellular", Loc.GetString("autodoc-damage-cellular") }
    };
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IResourceCache _cache;
    private EntityUid _spriteViewEntity;
    private static readonly EntProtoId BodyView = "AlertSpriteView";
    public event Action<AutodocUiButton>? OnAutodocButton;
    public event Action<string>? OnPartSelected;
    public event Action<string, string>? OnOperationSelected;
    public event Action? OnSurgeryBack;
    private string? _selectedPartId;
    public SiriusAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("autodoc-window-title");

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _cache = dependencies.Resolve<IResourceCache>();

        ApplyBackgroundStyles();
        WireButtons();
        SetInitialButtonStates();
        OnClose += () => OnAutodocButton?.Invoke(AutodocUiButton.Close);
    }
    private void ApplyBackgroundStyles()
    {
        var brightLine = new StyleBoxFlat(Color.FromHex("#1a5c1a"));
        var dimLine = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepTop.PanelOverride = brightLine;
        SepMid1.PanelOverride = dimLine;
        SepMid2.PanelOverride = dimLine;
        SepMid3.PanelOverride = dimLine;
        SepMid4.PanelOverride = dimLine;
        SepBottom.PanelOverride = dimLine;
        SepHumanoid.PanelOverride = dimLine;
    }
    private void WireButtons()
    {
        DoorOpenButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.OpenDoor);
        DoorCloseButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.CloseDoor);
        EjectBeakerButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectBeaker);
        EjectPatientButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectPatient);
        StartTreatmentButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.StartTreatment);
    }
    private void SetInitialButtonStates()
    {
        EjectBeakerButton.Disabled = true;
        EjectPatientButton.Disabled = true;
        StartTreatmentButton.Disabled = true;

        EjectBeakerButton.ModulateSelfOverride = ColorInactive;
        EjectPatientButton.ModulateSelfOverride = ColorInactive;
        StartTreatmentButton.ModulateSelfOverride = ColorInactive;

        SurgeryMainContainer.Visible = false;
        SurgeryProgressContainer.Visible = false;
        BodyPartsContainer.RemoveAllChildren();
        OperationsContainer.RemoveAllChildren();
    }
    public void UpdateState(AutodocBoundUserInterfaceState state)
    {
        _selectedPartId = state.SelectedPartId;
        UpdatePatientInfo(state);
        UpdateDamageDisplay(state);
        UpdateSurgeryPanel(state);
        UpdateStimulantsDisplay(state);
        UpdateDoorButtonsState(state);
        UpdateActionButtonsState(state);
        UpdateProgressDisplay(state);
        UpdateFooter(state);
    }
    private void UpdateSurgeryPanel(AutodocBoundUserInterfaceState state)
    {
        if (!state.HasOccupant || !state.CanSurgery || state.IsTreating)
        {
            SurgeryMainContainer.Visible = false;
            SepHumanoid.Visible = false;
            return;
        }
        if (state.IsOpen)
        {
            SurgeryMainContainer.Visible = false;
            SepHumanoid.Visible = false;
            return;
        }
        SurgeryMainContainer.Visible = true;
        SepHumanoid.Visible = true;
        UpdateBodyPartsList(state);
        UpdateOperationsList(state);
        UpdateSurgeryProgress(state);
    }
    private void UpdateBodyPartsList(AutodocBoundUserInterfaceState state)
    {
        BodyPartsContainer.RemoveAllChildren();
        _selectedPartId = state.SelectedPartId;
        if (state.BodyParts == null || state.BodyParts.Count == 0)
        {
            var label = new Label
            {
                Text = Loc.GetString("autodoc-surgery-no-parts"),
                FontColorOverride = ColorDim,
                StyleClasses = { "monospace" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 10, 0, 10)
            };
            BodyPartsContainer.AddChild(label);
            return;
        }
        foreach (var part in state.BodyParts)
        {
            var button = new Button
            {
                Text = part.DisplayName,
                HorizontalExpand = true,
                Disabled = !part.IsPresent,
                ModulateSelfOverride = part.IsPresent ? (part.HasDamage ? ColorModerate : ColorActive) : ColorDim,
                Margin = new Thickness(0, 1, 0, 1)
            };
            if (part.IsPresent)
            {
                button.OnPressed += _ =>
                {
                    _selectedPartId = part.Id;
                    OnPartSelected?.Invoke(part.Id);
                };
            }
            else
            {
                button.ToolTip = Loc.GetString("autodoc-surgery-part-missing");
            }
            if (_selectedPartId == part.Id)
            {
                button.ModulateSelfOverride = Color.FromHex("#55FF55");
                button.Modulate = Color.White;
            }
            BodyPartsContainer.AddChild(button);
        }
    }
    private void UpdateOperationsList(AutodocBoundUserInterfaceState state)
    {
        OperationsContainer.RemoveAllChildren();

        if (string.IsNullOrEmpty(state.SelectedPartId))
        {
            var label = new Label
            {
                Text = Loc.GetString("autodoc-surgery-select-part"),
                FontColorOverride = ColorDim,
                StyleClasses = { "monospace" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 10, 0, 10)
            };
            OperationsContainer.AddChild(label);
            SelectedPartLabel.Text = Loc.GetString("autodoc-surgery-no-part-selected");
            SelectedPartLabel.FontColorOverride = ColorDim;
            return;
        }
        var selectedPart = state.BodyParts?.FirstOrDefault(p => p.Id == state.SelectedPartId);
        SelectedPartLabel.Text = selectedPart != null
            ? Loc.GetString("autodoc-surgery-part-selected", ("part", selectedPart.DisplayName))
            : Loc.GetString("autodoc-surgery-no-part-selected");
        SelectedPartLabel.FontColorOverride = ColorActive;

        if (state.AvailableOperations == null || state.AvailableOperations.Count == 0)
        {
            var label = new Label
            {
                Text = Loc.GetString("autodoc-surgery-no-operations"),
                FontColorOverride = ColorDim,
                StyleClasses = { "monospace" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 10, 0, 10)
            };
            OperationsContainer.AddChild(label);
            return;
        }
        foreach (var op in state.AvailableOperations)
        {
            var button = new Button
            {
                Text = op.DisplayName,
                HorizontalExpand = true,
                Disabled = !op.IsAvailable || state.IsOperating,
                ModulateSelfOverride = op.IsAvailable ? ColorActive : ColorDim,
                Margin = new Thickness(0, 1, 0, 1),
                ToolTip = op.Tooltip ?? ""
            };

            if (op.IsAvailable && !state.IsOperating)
            {
                var partId = state.SelectedPartId;
                var opId = op.Id;
                button.OnPressed += _ => OnOperationSelected?.Invoke(partId, opId);
            }

            OperationsContainer.AddChild(button);
        }
    }
    private void UpdateSurgeryProgress(AutodocBoundUserInterfaceState state)
    {
        if (state.IsOperating)
        {
            SurgeryProgressContainer.Visible = true;
            SurgeryProgressBar.Value = state.OperationProgress * 100;
            SurgeryProgressPercentLabel.Text = $"{state.OperationProgress * 100:F0}%";
            if (!string.IsNullOrEmpty(state.CurrentOperationName))
            {
                SurgeryProgressLabel.Text = state.CurrentOperationName;
            }
        }
        else
        {
            SurgeryProgressContainer.Visible = false;
            SurgeryProgressBar.Value = 0;
            SurgeryProgressPercentLabel.Text = "0%";
            SurgeryProgressLabel.Text = Loc.GetString("autodoc-surgery-progress");
        }
    }
    private void UpdatePatientInfo(AutodocBoundUserInterfaceState state)
    {
        if (state.HasOccupant && !string.IsNullOrEmpty(state.OccupantName))
        {
            PatientNameLabel.Text = state.OccupantName.ToUpperInvariant();
            PatientNameLabel.FontColorOverride = ColorActive;
            var statusText = state.OccStatus switch
            {
                OccupantStatus.Alive => Loc.GetString("autodoc-status-alive"),
                OccupantStatus.Critical => Loc.GetString("autodoc-status-critical"),
                OccupantStatus.Dead => Loc.GetString("autodoc-status-dead"),
                _ => Loc.GetString("autodoc-status-unknown")
            };
            StatusLabel.Text = statusText;
            StatusLabel.FontColorOverride = state.OccStatus switch
            {
                OccupantStatus.Alive => ColorMinor,
                OccupantStatus.Critical => ColorModerate,
                OccupantStatus.Dead => ColorCritical,
                _ => ColorDim
            };
        }
        else
        {
            PatientNameLabel.Text = Loc.GetString("autodoc-no-patient");
            PatientNameLabel.FontColorOverride = ColorDim;
            StatusLabel.Text = Loc.GetString("autodoc-status-awaiting");
            StatusLabel.FontColorOverride = ColorDim;
        }
    }
    private void UpdateDamageDisplay(AutodocBoundUserInterfaceState state)
    {
        DamageContainer.RemoveAllChildren();
        if (!state.HasOccupant)
        {
            var emptyLabel = MakeDiagnosticLine(Loc.GetString("autodoc-damage-no-patient"), ColorDim);
            DamageContainer.AddChild(emptyLabel);
            return;
        }
        if (state.OccupantDamage == null || state.OccupantDamage.Count == 0)
        {
            var emptyLabel = MakeDiagnosticLine(Loc.GetString("autodoc-damage-none"), ColorDim);
            DamageContainer.AddChild(emptyLabel);
            return;
        }
        var maxDamage = state.OccupantDamage.Values.Max(x => x.Float());
        maxDamage = Math.Max(maxDamage, 100f);

        var sortedDamage = state.OccupantDamage
            .OrderByDescending(x => x.Value.Float())
            .ToList();
        foreach (var kvp in sortedDamage)
        {
            var damageType = kvp.Key;
            var amount = kvp.Value;

            if (amount <= 0) continue;

            var displayName = _damageDisplayNames.GetValueOrDefault(damageType, damageType.ToUpperInvariant());
            var color = GetDamageColor(amount.Float());

            DamageContainer.AddChild(MakeDamageLine(displayName, amount.Float(), color, maxDamage));
        }
    }
    private BoxContainer MakeDamageLine(string damageName, float amount, Color color, float maxDamage)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2)
        };
        var nameLabel = new Label
        {
            Text = $"[ {damageName} ]",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 140
        };
        var barBg = new PanelContainer
        {
            MinWidth = 120,
            MinHeight = 12,
            HorizontalExpand = false,
            PanelOverride = new StyleBoxFlat(Color.FromHex("#1a3a1a"))
        };
        var barWidth = 120f * Math.Clamp(amount / maxDamage, 0.05f, 1f);
        var fillPanel = new PanelContainer
        {
            MinWidth = barWidth,
            MinHeight = 12,
            PanelOverride = new StyleBoxFlat(color)
        };
        barBg.AddChild(fillPanel);
        var amountLabel = new Label
        {
            Text = $"{amount:F0}",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 50,
            HorizontalAlignment = HAlignment.Right
        };
        container.AddChild(nameLabel);
        container.AddChild(barBg);
        container.AddChild(amountLabel);
        return container;
    }
    private Label MakeDiagnosticLine(string text, Color color)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 8, 0, 8)
        };
    }
    private Color GetDamageColor(float amount)
    {
        if (amount >= 75) return ColorCritical;
        if (amount >= 50) return ColorSevere;
        if (amount >= 25) return ColorModerate;
        if (amount > 0) return ColorMinor;
        return ColorDim;
    }
    private void UpdateStimulantsDisplay(AutodocBoundUserInterfaceState state)
    {
        if (state.HasBeaker)
        {
            var amount = state.BeakerStimulantsAmount.Float();
            StimulantsLabel.Text = $"{amount:F1}";
            StimulantsLabel.FontColorOverride = amount >= 30 ? ColorMinor : ColorModerate;
        }
        else
        {
            StimulantsLabel.Text = Loc.GetString("autodoc-stimulants-none");
            StimulantsLabel.FontColorOverride = ColorDim;
        }
    }
    private void UpdateDoorButtonsState(AutodocBoundUserInterfaceState state)
    {
        var disabled = state.IsTreating;
        DoorOpenButton.Disabled = disabled || state.IsOpen;
        DoorCloseButton.Disabled = disabled || !state.IsOpen;
        DoorOpenButton.ModulateSelfOverride = (disabled || state.IsOpen) ? ColorInactive : null;
        DoorCloseButton.ModulateSelfOverride = (disabled || !state.IsOpen) ? ColorInactive : null;
        DoorOpenButton.Text = state.IsOpen ? Loc.GetString("autodoc-door-open") : Loc.GetString("autodoc-door-open-button");
        DoorCloseButton.Text = !state.IsOpen ? Loc.GetString("autodoc-door-closed") : Loc.GetString("autodoc-door-close-button");
    }

    private void UpdateActionButtonsState(AutodocBoundUserInterfaceState state)
    {
        var ejectPatientDisabled = !state.HasOccupant || state.IsTreating || !state.IsOpen;
        var ejectBeakerDisabled = !state.HasBeaker || state.IsTreating;
        var startDisabled = !state.TreatButtonEnabled || state.IsTreating || state.IsOpen;
        EjectBeakerButton.Disabled = ejectBeakerDisabled;
        EjectPatientButton.Disabled = ejectPatientDisabled;
        StartTreatmentButton.Disabled = startDisabled;
        EjectBeakerButton.ModulateSelfOverride = ejectBeakerDisabled ? ColorInactive : null;
        EjectPatientButton.ModulateSelfOverride = ejectPatientDisabled ? ColorInactive : null;
        StartTreatmentButton.ModulateSelfOverride = startDisabled ? ColorInactive : null;
        StartTreatmentButton.Text = state.IsTreating
            ? Loc.GetString("autodoc-treatment-progress")
            : Loc.GetString("autodoc-start-treatment");
    }
    private void UpdateProgressDisplay(AutodocBoundUserInterfaceState state)
    {
        if (state.IsTreating && state.TreatmentProgress > 0)
        {
            ProgressContainer.Visible = true;
            TreatmentProgress.Value = state.TreatmentProgress * 100;
            ProgressPercentLabel.Text = $"{state.TreatmentProgress * 100:F0}%";
        }
        else
        {
            ProgressContainer.Visible = false;
            TreatmentProgress.Value = 0;
            ProgressPercentLabel.Text = "0%";
        }
    }
    private void UpdateFooter(AutodocBoundUserInterfaceState state)
    {
        if (state.IsOperating)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-surgery");
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (state.IsTreating)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-treatment");
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (!state.Powered)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-no-power");
            FooterLabel.FontColorOverride = ColorCritical;
        }
        else if (state.HasOccupant && state.IsOpen)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-door-open");
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (state.HasOccupant && !state.TreatButtonEnabled)
        {
            var required = 30;
            var current = state.BeakerStimulantsAmount.Float();
            FooterLabel.Text = Loc.GetString("autodoc-footer-insufficient-stimulants",
                ("required", required),
                ("current", current));
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (state.HasOccupant && !state.IsOpen)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-ready");
            FooterLabel.FontColorOverride = ColorMinor;
        }
        else
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-ready");
            FooterLabel.FontColorOverride = ColorDim;
        }
    }
}
public enum AutodocSurgeryButton
{
    StartAll,
    SurgeryPart,
    EjectPart,
    Close
}
