// #Misfits Change - Wasteland Map Viewer Window
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Mobs;
using Content.Shared._Misfits.Overwatch;
using Content.Shared._Misfits.WastelandMap;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.WastelandMap;

[GenerateTypedNameReferences]
public sealed partial class WastelandMapWindow : FancyWindow
{
    private const string TermGreen = "#33FF33";
    private const string TermDimGreen = "#1a5c1a";

    public event Action<WastelandMapAnnotation>? OnAddAnnotation;
    public event Action<int>? OnRemoveAnnotation;
    public event Action? OnClearAnnotations;
    public event Action<OverwatchConsoleMessageType, uint?>? OnOverwatchAction;

    private readonly MapViewerControl _mapViewer;
    private readonly Dictionary<string, bool> _overwatchGroupExpanded = new();
    private readonly FixedEye _overwatchDefaultEye = new();
    private readonly FixedEye _overwatchFeedEye = new();
    private ResPath? _loadedTexturePath;
    private Robust.Shared.Maths.Box2 _loadedBounds;
    private bool _hasLoadedMap;
    private OverwatchConsoleState? _overwatchState;
    private IEye? _overwatchSourceEye;

    public WastelandMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mapViewer = new MapViewerControl
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        _mapViewer.OnAddAnnotation += annotation => OnAddAnnotation?.Invoke(annotation);
        _mapViewer.OnRemoveAnnotation += index => OnRemoveAnnotation?.Invoke(index);
        _mapViewer.OnClearAnnotations += () => OnClearAnnotations?.Invoke();
        MapContainer.AddChild(_mapViewer);

        SepOverwatch.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        OverwatchCameraFallback.PanelOverride = new StyleBoxFlat(Color.FromHex("#050805"));
        OverwatchCameraView.ViewportSize = new Vector2i(640, 360);
        OverwatchCameraView.Eye = _overwatchDefaultEye;
        LayoutContainer.SetAnchorPreset(OverwatchCameraView, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(OverwatchCameraFallback, LayoutContainer.LayoutPreset.Wide);

        MapTabButton.OnPressed += _ => SwitchToMap();
        OverwatchTabButton.OnPressed += _ => SwitchToOverwatch();
        OverwatchStopWatchingButton.OnPressed += _ => OnOverwatchAction?.Invoke(OverwatchConsoleMessageType.Unwatch, null);
        OverwatchSearchBar.OnTextChanged += _ => RefreshOverwatchView();

        PanModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.None);
            FooterText.Text = "Scroll to zoom | Click and drag to pan | Right click an annotation to delete it";
        };

        MarkerModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Marker);
            FooterText.Text = "Marker mode: left click on the map to place a labeled marker";
        };

        BoxModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Box);
            FooterText.Text = "Box mode: drag on the map to draw a labeled box";
        };

        DrawModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Draw);
            FooterText.Text = "Draw mode: click and drag to freehand draw. Use the color swatches to change color";
        };

        EraseButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Erase);
            FooterText.Text = "Erase mode: hover over an annotation and left click to delete it. Right click also works in any mode";
        };

        ClearMapButton.OnPressed += _ => _mapViewer.ClearAnnotations();
        AnnotationText.OnTextChanged += args => _mapViewer.SetPendingAnnotationText(args.Text);
        _mapViewer.SetPendingAnnotationText(AnnotationText.Text);

        // Color swatches
        var swatches = new (Color Color, string Name)[]
        {
            (new Color(0.95f, 0.50f, 0.15f, 1f), "Orange"),
            (new Color(0.87f, 0.15f, 0.15f, 1f), "Red"),
            (new Color(0.94f, 0.88f, 0.10f, 1f), "Yellow"),
            (new Color(0.20f, 0.80f, 0.25f, 1f), "Green"),
            (new Color(0.20f, 0.60f, 1.00f, 1f), "Blue"),
            (new Color(1.00f, 1.00f, 1.00f, 1f), "White"),
        };
        ColorRow.AddChild(new Label { Text = "Color: " });
        foreach (var (swatch, name) in swatches)
        {
            var captured = swatch;
            var btn = new Button { Text = "\u25a0", ToolTip = name };
            btn.ModulateSelfOverride = swatch;
            btn.OnPressed += _ => _mapViewer.SetAnnotationColor(captured);
            ColorRow.AddChild(btn);
        }

        // Stroke-width presets
        ColorRow.AddChild(new Label { Text = "  Width: " });
        foreach (var (pixels, label) in new (float, string)[] { (2f, "Thin"), (4f, "Med"), (8f, "Thick"), (12f, "Max") })
        {
            var pw = pixels;
            var wb = new Button { Text = label };
            wb.OnPressed += _ => _mapViewer.SetAnnotationStrokeWidth(pw);
            ColorRow.AddChild(wb);
        }
    }

    public void SetMap(string title, ResPath texturePath, Robust.Shared.Maths.Box2 worldBounds, WastelandMapTrackedBlip[] trackedBlips, WastelandMapAnnotation[] sharedAnnotations, bool compactHud)
    {
        MapTitle.Text = title;
        Title = title;
        ToolbarContainer.Visible = !compactHud;
        FooterContainer.Visible = true;

        if (!_hasLoadedMap || _loadedTexturePath != texturePath || _loadedBounds != worldBounds)
        {
            var resourceCache = IoCManager.Resolve<IResourceCache>();
            var fullPath = new ResPath("/Textures") / texturePath;

            if (resourceCache.TryGetResource<TextureResource>(fullPath, out var textureResource))
            {
                _mapViewer.SetTexture(textureResource.Texture, worldBounds);
                _loadedTexturePath = texturePath;
                _loadedBounds = worldBounds;
                _hasLoadedMap = true;
            }
        }

        _mapViewer.SetTrackedBlips(trackedBlips);
        _mapViewer.SetAnnotations(sharedAnnotations);
    }

    public void UpdateOverwatch(OverwatchConsoleState? state, IEye? eye)
    {
        _overwatchState = state;
        _overwatchSourceEye = eye;
        ModeBar.Visible = state != null;

        if (state == null)
        {
            _overwatchSourceEye = null;
            UpdateOverwatchCamera(null);
            SwitchToMap();
            return;
        }

        OverwatchHeaderLabel.Text = state.MonitorTitle;
        UpdateOverwatchCamera(eye);
        RefreshOverwatchView();
    }

    private void SwitchToMap()
    {
        MapPanel.Visible = true;
        OverwatchPanel.Visible = false;
    }

    private void SwitchToOverwatch()
    {
        if (_overwatchState == null)
            return;

        MapPanel.Visible = false;
        OverwatchPanel.Visible = true;
        RefreshOverwatchView();
    }

    private void RefreshOverwatchView()
    {
        if (_overwatchState == null)
            return;

        var search = OverwatchSearchBar.Text.Trim();
        var visibleEntries = string.IsNullOrWhiteSpace(search)
            ? _overwatchState.Personnel
            : _overwatchState.Personnel
                .Where(entry =>
                    entry.Name.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                    (!string.IsNullOrWhiteSpace(entry.JobTitle) &&
                     entry.JobTitle.Contains(search, StringComparison.OrdinalIgnoreCase)) ||
                    entry.Category.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                    entry.Number.ToString("D4").Contains(search, StringComparison.OrdinalIgnoreCase))
                .ToList();

        OverwatchNoPersonnelLabel.Visible = visibleEntries.Count == 0;
        OverwatchStopWatchingButton.Disabled = _overwatchState.WatchedNumber == null;
        SetMarkup(OverwatchRosterSummaryLabel,
            _overwatchState.Personnel.Count == 0
                ? $"[color={TermDimGreen}]No linked personnel detected.[/color]"
                : $"[color={TermGreen}]{visibleEntries.Count} of {_overwatchState.Personnel.Count} linked personnel visible.[/color]");

        var hasCurrent = _overwatchState.WatchedNumber != null &&
                         _overwatchState.Personnel.Any(entry => entry.Number == _overwatchState.WatchedNumber.Value);

        if (hasCurrent)
        {
            SetMarkup(OverwatchStatusLabel,
                $"[color={TermGreen}]SOUND[/color] live   [color={TermGreen}]CAMERA[/color] live");
        }
        else if (_overwatchState.WatchedNumber != null && HasLastKnownOverwatchPosition())
        {
            SetMarkup(OverwatchStatusLabel,
                $"[color={TermGreen}]SOUND[/color] lost   [color={TermGreen}]CAMERA[/color] lost   [color={TermDimGreen}]Last known:[/color] {FormattedMessage.EscapeText(GetLastKnownOverwatchText())}");
        }
        else
        {
            SetMarkup(OverwatchStatusLabel,
                $"[color={TermGreen}]SOUND[/color] idle   [color={TermGreen}]CAMERA[/color] idle");
        }

        OverwatchPersonnelList.RemoveAllChildren();
        foreach (var group in visibleEntries
                     .OrderBy(entry => entry.CategorySortOrder)
                     .ThenBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
                     .GroupBy(entry => entry.Category))
        {
            var groupName = group.Key;
            var bodyContents = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 6,
                Margin = new Thickness(8, 4, 8, 8),
                HorizontalExpand = true,
            };

            foreach (var entry in group)
                bodyContents.AddChild(MakeOverwatchRow(entry));

            var heading = new CollapsibleHeading($"{groupName} [{group.Count()}]")
            {
                MinHeight = 28,
                HorizontalExpand = true,
            };
            heading.AddStyleClass(ContainerButton.StyleClassButton);
            heading.Label.HorizontalExpand = true;
            heading.Label.HorizontalAlignment = HAlignment.Left;

            var body = new CollapsibleBody
            {
                HorizontalExpand = true,
                Children =
                {
                    bodyContents
                }
            };

            var collapsible = new Collapsible(heading, body)
            {
                HorizontalExpand = true,
                BodyVisible = !_overwatchGroupExpanded.TryGetValue(groupName, out var expanded)
                    ? string.IsNullOrWhiteSpace(search) || group.Any(entry => entry.IsCurrentTarget)
                    : expanded,
            };

            heading.OnToggled += args => _overwatchGroupExpanded[groupName] = args.Pressed;
            OverwatchPersonnelList.AddChild(collapsible);
        }
    }

    private Control MakeOverwatchRow(OverwatchConsoleEntry entry)
    {
        var active = entry.IsCurrentTarget;
        var row = new ContainerButton
        {
            HorizontalExpand = true,
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex(active ? "#0a130a" : "#050805"),
                BorderColor = Color.FromHex(active ? TermGreen : "#0f3d0f"),
                BorderThickness = active ? new Thickness(4, 1, 1, 1) : new Thickness(1),
            },
        };
        row.OnPressed += _ => OnOverwatchAction?.Invoke(
            active ? OverwatchConsoleMessageType.Unwatch : OverwatchConsoleMessageType.Watch,
            entry.Number);

        var contents = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            Margin = new Thickness(6, 4, 6, 4),
        };
        row.AddChild(contents);

        var title = new RichTextLabel { HorizontalExpand = true };
        SetMarkup(title,
            $"[color={TermGreen}][bold]> {FormattedMessage.EscapeText(entry.Name ?? "UNKNOWN")}[/bold][/color] [color={TermDimGreen}]#{entry.Number:D4}[/color]");
        contents.AddChild(title);

        var detail = new RichTextLabel { HorizontalExpand = true };
        SetMarkup(detail,
            $"[color={TermDimGreen}]{FormattedMessage.EscapeText(string.IsNullOrWhiteSpace(entry.JobTitle) ? "Unknown role" : entry.JobTitle!)}[/color]");
        contents.AddChild(detail);

        var bottom = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        contents.AddChild(bottom);

        var healthBar = new ProgressBar
        {
            MinValue = 0f,
            MaxValue = 1f,
            Value = entry.Health,
            MinHeight = 12,
            HorizontalExpand = true,
        };
        UpdateHealthBarStyle(healthBar, entry.Health, entry.State);
        bottom.AddChild(healthBar);

        bottom.AddChild(new Label
        {
            Text = GetOverwatchStateLabel(entry.State),
            StyleClasses = { "monospace" },
            FontColorOverride = GetOverwatchStateColor(entry.State),
            MinWidth = 88,
            HorizontalAlignment = HAlignment.Right,
        });

        return row;
    }

    private void UpdateOverwatchCamera(IEye? eye)
    {
        var hasFeed = eye != null;
        OverwatchCameraView.Eye = hasFeed ? _overwatchFeedEye : _overwatchDefaultEye;
        OverwatchCameraView.Visible = hasFeed;
        OverwatchCameraFallback.Visible = !hasFeed;

        var hasCurrent = TryGetCurrentOverwatchEntry(out _);
        var hasLastKnown = _overwatchState?.WatchedNumber != null && HasLastKnownOverwatchPosition();
        OverwatchCameraFallbackLabel.Text = hasCurrent
            ? "CAMERA FEED UNAVAILABLE"
            : hasLastKnown
                ? $"FEED LOST\nLAST KNOWN {GetLastKnownOverwatchText()}"
                : "NO ACTIVE CAMERA FEED";
        OverwatchSignalLabel.Text = hasCurrent
            ? "SECURE LINK ACTIVE"
            : hasLastKnown
                ? "LAST KNOWN LOCK"
                : "SECURE LINK STANDBY";
        OverwatchSignalLabel.FontColorOverride = Color.FromHex(hasCurrent || hasLastKnown ? TermGreen : TermDimGreen);
        SyncOverwatchFeedEye();
    }

    private void SyncOverwatchFeedEye()
    {
        if (_overwatchSourceEye == null)
            return;

        _overwatchFeedEye.Position = _overwatchSourceEye.Position;
        _overwatchFeedEye.Offset = _overwatchSourceEye.Offset;
        _overwatchFeedEye.Rotation = _overwatchSourceEye.Rotation;
        _overwatchFeedEye.Zoom = _overwatchSourceEye.Zoom;
        _overwatchFeedEye.DrawFov = _overwatchSourceEye.DrawFov;
        _overwatchFeedEye.DrawLight = _overwatchSourceEye.DrawLight;
    }

    private bool TryGetCurrentOverwatchEntry(out OverwatchConsoleEntry entry)
    {
        entry = default;

        if (_overwatchState?.WatchedNumber == null)
            return false;

        foreach (var personnel in _overwatchState.Personnel)
        {
            if (personnel.Number != _overwatchState.WatchedNumber.Value)
                continue;

            entry = personnel;
            return true;
        }

        return false;
    }

    private bool HasLastKnownOverwatchPosition()
    {
        return _overwatchState?.LastKnownX != null &&
               _overwatchState.LastKnownY != null &&
               !string.IsNullOrWhiteSpace(_overwatchState.LastKnownTimestamp);
    }

    private string GetLastKnownOverwatchText()
    {
        if (_overwatchState?.LastKnownX == null ||
            _overwatchState.LastKnownY == null ||
            string.IsNullOrWhiteSpace(_overwatchState.LastKnownTimestamp))
        {
            return "UNAVAILABLE";
        }

        return $"{_overwatchState.LastKnownX.Value:0.0}, {_overwatchState.LastKnownY.Value:0.0} @ {_overwatchState.LastKnownTimestamp}";
    }

    private static void UpdateHealthBarStyle(ProgressBar bar, float health, MobState state)
    {
        bar.BackgroundStyleBoxOverride ??= new StyleBoxFlat(Color.FromHex("#081108"));
        bar.ForegroundStyleBoxOverride ??= new StyleBoxFlat(Color.FromHex(TermGreen));

        var foreground = (StyleBoxFlat) bar.ForegroundStyleBoxOverride;
        foreground.BackgroundColor = state switch
        {
            MobState.Dead => Color.FromHex("#7a1010"),
            MobState.Critical or MobState.SoftCritical => Color.FromHex("#c88412"),
            _ when health <= 0.35f => Color.FromHex("#c8c812"),
            _ => Color.FromHex(TermGreen),
        };
    }

    private static string GetOverwatchStateLabel(MobState state)
    {
        return state switch
        {
            MobState.Alive => "STABLE",
            MobState.Critical => "CRITICAL",
            MobState.SoftCritical => "DOWN",
            MobState.Dead => "DECEASED",
            _ => "STANDBY",
        };
    }

    private static Color GetOverwatchStateColor(MobState state)
    {
        return state switch
        {
            MobState.Alive => Color.FromHex(TermGreen),
            MobState.Critical => Color.FromHex("#ffb347"),
            MobState.SoftCritical => Color.FromHex("#c8c812"),
            MobState.Dead => Color.FromHex("#d94b4b"),
            _ => Color.FromHex(TermDimGreen),
        };
    }

    private static void SetMarkup(RichTextLabel label, string markup)
    {
        var message = new FormattedMessage();
        message.AddMarkupPermissive(markup);
        label.SetMessage(message);
    }
}
