using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Administration.WhitelistLogs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.WhitelistLogs;

[GenerateTypedNameReferences]
public sealed partial class WhitelistLogsWindow : FancyWindow
{
    public WhitelistLogsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<WhitelistLogEntry> entries)
    {
        LogList.RemoveAllChildren();

        if (entries.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = "No whitelist actions have been logged yet.",
                Margin = new Thickness(0, 8, 0, 0),
                FontColorOverride = Color.Gray
            };
            LogList.AddChild(emptyLabel);
            return;
        }

        foreach (var entry in entries)
        {
            LogList.AddChild(BuildEntryRow(entry));
        }
    }

    private static PanelContainer BuildEntryRow(WhitelistLogEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 12,
            Margin = new Thickness(0, 2)
        };

        var bgPanel = new PanelContainer();
        bgPanel.AddChild(row);

        row.AddChild(new Label
        {
            Text = FormatTime(entry.Time),
            MinWidth = 90,
            ClipText = true
        });

        row.AddChild(new Label
        {
            Text = entry.Action,
            MinWidth = 80,
            ClipText = true
        });

        row.AddChild(new Label
        {
            Text = entry.AdminName,
            MinWidth = 170,
            ClipText = true
        });

        row.AddChild(new Label
        {
            Text = entry.TargetName,
            MinWidth = 170,
            ClipText = true
        });

        row.AddChild(new Label
        {
            Text = entry.Roles,
            MinWidth = 220,
            ClipText = true
        });

        row.AddChild(new Label
        {
            Text = BuildDetailText(entry),
            MinWidth = 420,
            ClipText = true
        });

        return bgPanel;
    }

    private static string BuildDetailText(WhitelistLogEntry entry)
    {
        var reason = string.IsNullOrWhiteSpace(entry.Reason) ? "-" : entry.Reason;
        var discord = string.IsNullOrWhiteSpace(entry.DiscordUsername) ? "-" : entry.DiscordUsername;
        var application = string.IsNullOrWhiteSpace(entry.ApplicationText) ? "-" : entry.ApplicationText;
        return $"Reason: {reason} | Discord: {discord} | Application: {application}";
    }

    private static string FormatTime(TimeSpan time)
    {
        var totalSeconds = (int) time.TotalSeconds;
        var hours = totalSeconds / 3600;
        var minutes = (totalSeconds % 3600) / 60;
        var seconds = totalSeconds % 60;
        return $"{hours:D2}:{minutes:D2}:{seconds:D2}";
    }
}
