// SPDX-License-Identifier: AGPL-3.0-or-later

global using Robust.Client.AutoGenerated;
global using Robust.Client.UserInterface;
global using Robust.Client.UserInterface.Controls;
global using Robust.Client.UserInterface.XAML;
