// #Misfits Add - Mandatory acknowledgement window shown to raid participants at conclusion.

using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.RaidRequest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.RaidRequest.UI;

[GenerateTypedNameReferences]
public sealed partial class RaidConcludedWindow : FancyWindow
{
    public event Action? OnAcknowledged;

    private bool _mayClose;

    public RaidConcludedWindow()
    {
        RobustXamlLoader.Load(this);

        // This notice must be explicitly acknowledged; do not expose the title-bar X.
        CloseButton.Visible = false;
        AcknowledgeButton.OnPressed += _ =>
        {
            _mayClose = true;
            Close();
            OnAcknowledged?.Invoke();
        };
    }

    public void Populate(RaidRequestEntry entry)
    {
        var requester = RaidRequestConfig.FactionDisplayName(entry.RequesterFaction);
        var target = RaidRequestConfig.FactionDisplayName(entry.TargetFaction);

        HeaderLabel.SetMarkup(
            $"[color=#FF5555][bold]{FormattedMessage.EscapeText(Loc.GetString("raid-concluded-header", ("id", entry.Id)))}[/bold][/color]");
        PartiesLabel.SetMarkup(
            $"[color=#FFCC66]{FormattedMessage.EscapeText(Loc.GetString("raid-concluded-parties", ("from", requester), ("to", target)))}[/color]");
    }

    public override void Close()
    {
        if (_mayClose)
            base.Close();
    }

    public void ForceClose()
    {
        _mayClose = true;
        base.Close();
    }
}
