// #Misfits Add - Door Logs admin panel code-behind
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Administration.DoorLogs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.DoorLogs;

[GenerateTypedNameReferences]
public sealed partial class DoorLogsWindow : FancyWindow
{
    public DoorLogsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Fills the log list with entries from the server.
    /// </summary>
    public void Populate(List<DoorLogEntry> entries)
    {
        LogList.RemoveAllChildren();

        if (entries.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = "No doors have been destroyed yet.",
                Margin = new Thickness(0, 8, 0, 0),
                FontColorOverride = Color.Gray
            };
            LogList.AddChild(emptyLabel);
            return;
        }

        foreach (var entry in entries)
        {
            var row = BuildEntryRow(entry);
            LogList.AddChild(row);
        }
    }

    private static PanelContainer BuildEntryRow(DoorLogEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 12,
            Margin = new Thickness(0, 2)
        };

        // Alternating row background for readability
        var bgPanel = new PanelContainer();
        bgPanel.AddChild(row);

        var timeLabel = new Label
        {
            Text = FormatTime(entry.Time),
            MinWidth = 160,
            ClipText = true
        };
        row.AddChild(timeLabel);

        var doorLabel = new Label
        {
            Text = entry.DoorPrototype,
            MinWidth = 420,
            ClipText = true
        };
        row.AddChild(doorLabel);

        var whoLabel = new Label
        {
            Text = entry.DestroyedBy,
            MinWidth = 200,
            ClipText = true
        };
        row.AddChild(whoLabel);

        return bgPanel;
    }

    private static string FormatTime(TimeSpan time)
    {
        // Format as HH:mm:ss
        var totalSeconds = (int)time.TotalSeconds;
        var hours = totalSeconds / 3600;
        var minutes = (totalSeconds % 3600) / 60;
        var seconds = totalSeconds % 60;
        return $"{hours:D2}:{minutes:D2}:{seconds:D2}";
    }
}
